### ISSUE TITLE
Stagger Animation

### ISSUE THREAD

**Issue by AlbatiQue** [ivodolenc/nuxt-gsap-module#1]
Hey,

Seems like a great module for nuxt! 
Is it possible to do a Stagger animation and how would you impliment it?

Thanks

**Comment by ivodolenc** [comment]
Sure, here is an example:

```html
<!-- index.vue -->

<template>
  <div>
    <div class="box"></div>
    <div class="box"></div>
    <div class="box"></div>
  </div>
</template>

<script>
  export default {
    mounted() {
      this.staggering()
    },
    methods: {
      staggering() {
        const gsap = this.$gsap

        gsap.to('.box', {
          x: 300,
          stagger: 0.1,
        })
      },
    },
  }
</script>
```

More info can be found on the official [website](https://greensock.com/docs/v3/Staggers).

**Comment by ivodolenc** [comment]
Closing this since more than one example is provided. Also, feel free to check out other similar examples:

- [Code examples](https://github.com/ivodolenc/nuxt-gsap-module/tree/master/examples)
- [Codesandbox](https://codesandbox.io/s/example-nuxt-gsap-module-basic-bqi7c)
