### ISSUE TITLE
How to use TimelineLite？

### ISSUE THREAD

**Issue by jinxinkai** [ivodolenc/nuxt-gsap-module#11]

**Comment by ivodolenc** [comment]
Hi, according to official docs, [`TimelineLite`](https://greensock.com/timelinelite/) has been deprecated. But you can use [`gsap.timeline()`](https://greensock.com/docs/v3/GSAP/Timeline) instead:

**GSAP core**

```js
// Access GSAP by using
this.$gsap

// Box rotation
this.$gsap.to('.box', { rotation: 27, x: 100, duration: 1 })

// or
const gsap = this.$gsap
gsap.to('.box', { rotation: 27, x: 100, duration: 1 })
```

**GSAP Timeline**

```js
const tl = this.$gsap.timeline({ repeat: 2, repeatDelay: 1 })

tl.to('.box', { x: 100, duration: 1 })
tl.to('.box', { y: 50, duration: 1 })
tl.to('.box', { opacity: 0, duration: 1 })
```

**Comment by jinxinkai** [comment]
> Hi, according to official docs, [`TimelineLite`](https://greensock.com/timelinelite/) has been deprecated. But you can use [`gsap.timeline()`](https://greensock.com/docs/v3/GSAP/Timeline) instead:
> 
> **GSAP core**
> 
> ```js
> // Access GSAP by using
> this.$gsap
> 
> // Box rotation
> this.$gsap.to('.box', { rotation: 27, x: 100, duration: 1 })
> 
> // or
> const gsap = this.$gsap
> gsap.to('.box', { rotation: 27, x: 100, duration: 1 })
> ```
> 
> **GSAP Timeline**
> 
> ```js
> const tl = this.$gsap.timeline({ repeat: 2, repeatDelay: 1 })
> 
> tl.to('.box', { x: 100, duration: 1 })
> tl.to('.box', { y: 50, duration: 1 })
> tl.to('.box', { opacity: 0, duration: 1 })
> ```

thanks! I got it.

**Comment by ivodolenc** [comment]
Np 👍 Closing this as resolved.
