### ISSUE TITLE
Question - use $gsap prototype within plugin or global js file

### ISSUE THREAD

**Issue by pauloguerraf** [ivodolenc/nuxt-gsap-module#17]
Hi,

Thank you for your work on this module. 

I had a question regarding how to access the $gsap vue prototype from a js plugin
I am trying to register gsap effects using https://greensock.com/docs/v3/GSAP/gsap.registerEffect(). I have succesfully register effects from a component using `this.$gsap.registerEffect()`.. but wanted to clean up and organize my code a little bit better, and since gsap effects only need to be registered once to be used globally I thought about using a plugin for this, but whenever I use `this.$gsap` inside a plugin it is undefined. I don't have a lot of experience with nuxt plugins or independente js files so any tip or advice would be greatly appreciated.

Thank you in advance.

**Comment by ivodolenc** [comment]
Hi, I just added a new feature `registerEffect` to simplify global effect registration (`registerEffect` is an `Array`, so you can register multiple effects via that option).

There is no need to create a new plugin, just add your effect/s to the new option and that's it.

Until I update the documentation, here is a simple example:

**nuxt.config.js**

```js
export default {
  gsap: {
    registerEffect: [
      {
        name: 'fadeOut',
        defaults: {
          y: -100,
          opacity: 0,
          duration: 2
        },
        effect: (targets, config) => {
          // If you use eslint, add comments to disable and avoid errors for no-undef 'gsap'
          // eslint-disable-next-line no-undef
          return gsap.to(targets, {
            y: config.y,
            opacity: config.opacity,
            duration: config.duration
          })
        }
      }
    ]
  }
}
```

**index.vue**

```html
<template>
  <div>
    <h1 class="title">Nuxt GSAP Effect</h1>
  </div>
</template>

<script>
  export default {
    mounted() {
      this.applyCustomEffect()
    },
    methods: {
      applyCustomEffect() {
        this.$gsap.effects.fadeOut('.title')
      }
    }
  }
</script>
```

---

Available in the latest version: `1.4.0`

**Comment by ivodolenc** [comment]
I just updated the [docs](https://github.com/ivodolenc/nuxt-gsap-module#register-effect) and added a simple [example](https://github.com/ivodolenc/nuxt-gsap-module/tree/master/examples/register-effect).

I also tested it with `multiple effects` and it seems to work fine.

@pauloguerraf Feel free to try it and let me know if everything works as expected so this can be closed as resolved.

**Comment by pauloguerraf** [comment]
Thank you so much @ivodolenc! It works great!

**Comment by ivodolenc** [comment]
Awesome, closing this as resolved. Cheers! 👋

**Comment by seppeclijsters** [comment]
Thank you @ivodolenc for this plugin! 
I wonder how to add "scrolltrigger" in my registerEffect. I get an error **scrolltrigger is not defined**.
Thank you in advance!

**nuxt.config.js**

```
export default {
  gsap: {
    extraPlugins: {
      scrollTo: true,
      scrollTrigger: true
    },
    extraEases: {
      expoScaleEase: true
    },
    registerEffect: [
      {
        name: 'fadeIn',
        effect: (targets, config) => {
          return scrolltrigger.batch(targets, {
            onEnter: (batch, triggers) => {
                gsap.to(batch, {
                    // batchMax: 1,
                    scrollTrigger: {
                        trigger: batch, 
                        // markers: true,
                        toggleActions: "play none none none"
                    }, 
                    autoAlpha: 1, 
                    x: 0, 
                    stagger:0.5,
                    duration: .8
                });
            }     
        })
        }
      },
}
```

**index.vue**

```
<template>
  <div>
    <h1 class="title">Nuxt GSAP Effect</h1>
  </div>
</template>

<script>
  export default {
    mounted() {
      this.applyCustomEffect()
    },
    methods: {
      applyCustomEffect() {
        this.$gsap.effects.fadeIn('.title')
      }
    }
  }
</script>
```

**Comment by ivodolenc** [comment]
Hi @seppeclijsters , `ScrollTrigger` only works on the client side so you have to write the code inside `process.client` statement.

Here's a simple example just to get an idea of how to get started:

```js
// nuxt.config.js

export default {
  buildModules: ['nuxt-gsap-module'],

  gsap: {
    extraPlugins: {
      scrollTrigger: true
    },

    /* eslint-disable */
    registerEffect: [
      {
        name: 'scrollSlide',
        effect: targets => {
          // Client side code
          if (process.client) {
            const { ScrollTrigger } = require('gsap/ScrollTrigger')
            gsap.registerPlugin(ScrollTrigger)

            return ScrollTrigger.batch(targets, {
              onEnter: batch =>
                gsap.to(batch, {
                  x: 500,
                  duration: 1
                }),
              onEnterBack: batch =>
                gsap.to(batch, {
                  x: 0,
                  duration: 3
                })
            })
          }
        }
      }
    ]
    /* eslint-enable */
  }
}
```

```html
<template>
  <div>
    <div style="height: 100vh"></div>
    <h1 class="title">Nuxt GSAP Effect</h1>
    <div style="height: 300vh"></div>
  </div>
</template>

<script>
  export default {
    mounted() {
      this.applyCustomEffect()
    },
    methods: {
      applyCustomEffect() {
        this.$gsap.effects.scrollSlide('.title')
      }
    }
  }
</script>
```

**Comment by seppeclijsters** [comment]
Thank you soo much @ivodolenc, works like a charm!
