### ISSUE TITLE
Because I love you ♥ I want to contribute to add documentation for this Lovely Module!

### ISSUE THREAD

**Issue by sniperadmin** [ivodolenc/nuxt-gsap-module#20]
There are lots of frameworks to do the docs part, just let me know if you have something in mind (e.g. `nuxt content / docusaurus / vuepress / .... etc`

**Comment by ivodolenc** [comment]
Hi and thanks for your interest in this module.

Don't get me wrong but I don't think it's necessary to add a separate site for documentation at the moment. All options are explained in the [`README.md`](https://github.com/ivodolenc/nuxt-gsap-module/blob/master/README.md) file.

But feel free to give your opinion and comments on whether something needs to be added or edited.

**Comment by sniperadmin** [comment]
oh nice, no issues,.. I loved the idea anyways

**Comment by ivodolenc** [comment]
Thanks for the suggestion anyway. Closing this since there is no issues.
