### ISSUE TITLE
Error: Can't resolve 'gsap/DrawSVGPlugin' 

### ISSUE THREAD

**Issue by sniperadmin** [ivodolenc/nuxt-gsap-module#21]
### Summary

Getting this error when registering `drawSVG` into nuxt
![image](https://user-images.githubusercontent.com/24525973/133910617-9d38bebc-6c6a-4615-bca0-83c57a69d769.png)

### Steps done:
- `nuxt.config.js`:
```js
gsap: {
    extraPlugins: {},
    clubPlugins: {
      drawSVG: true,
    },
    registerEffect: []
  },
```
- using in template with directive:
```html
<circle v-gsap.from="{
      duration: 1,
      drawSVG: '0 100%'
  }" cx="121.89451" cy="325.76588" r="45" fill="#6c63ff"/>
```

I have checked how it is actually registered in the [module/templates/plugin](https://github.com/ivodolenc/nuxt-gsap-module/blob/1f04d9ec5a28612266f0d9c653c4ce9dba830c11/templates/plugin.js#L128):

```js
<% if (options.clubPlugins.drawSVG) { %>
    const { DrawSVGPlugin } = require('gsap/DrawSVGPlugin')
    inject('DrawSVGPlugin', DrawSVGPlugin)
    gsap.registerPlugin(DrawSVGPlugin)
<% } %>
```

I can't take vague assumptions at this point, but I am thinking that it might have some buggy behaviors 🤔

**Comment by ivodolenc** [comment]
[`DrawSVG`](https://github.com/ivodolenc/nuxt-gsap-module#drawsvg) is a premium plugin, so you must have a [`Club GreenSock`](https://github.com/ivodolenc/nuxt-gsap-module#club-greensock) membership to be able to use the premium plugins.

### Club GreenSock

`nuxt-gsap-module` supports Club GreenSock premium plugins. They can be easily activated via `module` settings, just like the free ones.

**Installation**

1. Follow the [official](https://youtu.be/30CivTsqqMY?t=87) instructions and install the `premium` plugins as usual.
2. After installation, simply activate the desired plugins and that's it, you're ready to go!

**Comment by sniperadmin** [comment]
Appreciate the response :), Aha! I see now, so for future, if anyone stucks at this point, we should subscribe first in a [premium Club GreenSock](https://greensock.com/club/)
![image](https://user-images.githubusercontent.com/24525973/133930740-138d6542-26ac-4fea-8431-8ad374f55893.png)

**Comment by ivodolenc** [comment]
This only applies to specific `premium` plugins. No need to emphasize this, I think everything is explained in the module documentation and on the official GSAP website.

You can use the module without a subscription. See [Licenses](https://github.com/ivodolenc/nuxt-gsap-module#license).

**Comment by Neocor89** [comment]
I have the same problem after using the DrawSvg plugin to animate a small image of my portfolio I find myself blocked after deploying it. I think it's a shame ☹️😞
