### ISSUE TITLE
Compatible with NuxtJS 3?

### ISSUE THREAD

**Issue by maximilian-schwarz** [ivodolenc/nuxt-gsap-module#24]
Is it compatible with Nuxtjs 3?

**Comment by ivodolenc** [comment]
Hi, I think `Nuxt3` is still in beta, so let's wait for the first official `production` version (it is possible that some part of the code or feature will change until the final version so there's no need to rush).

After `production-ready` release, I will adjust the module according to official guidelines to support the latest version of Nuxt.

Just to note, the module works fine in `Nuxt2` projects, and to be honest, I haven't tested it in Nuxt3 version yet 😃

For now, you can manually import `gsap` to your` Nuxt3` project.

**Comment by bonomite** [comment]
Thanks for the update.

**Comment by ivodolenc** [comment]
I reopening this for others to see. The module is still not compatible with `nuxt3` since there is no `production-ready` version.

**Comment by davidschubert** [comment]
and know??????

**Comment by ivodolenc** [comment]
@davidschubert ??

**Comment by davidschubert** [comment]
Sorry :-) my question is:

Is it compatible with Nuxtjs 3? Or better question. When are you starting to get it compatible with nuxt 3? there is already the release candidate of nuxt3 in v8. It would be just great to use this module.

Or do you have any other idea how to implement gsap3 with smoothscroller into nuxt3?

**Comment by ivodolenc** [comment]
@davidschubert Ok, just in case, I'll bump this [comment](https://github.com/ivodolenc/nuxt-gsap-module/issues/24#issuecomment-995795968) and this [comment](https://github.com/ivodolenc/nuxt-gsap-module/issues/24#issuecomment-1120439984) above.

...

> Hi, I think Nuxt3 is still in beta, so let's wait for the first official production version (it is possible that some part of the code or feature will change until the final version so there's no need to rush).

> After production-ready release, I will adjust the module according to official guidelines to support the latest version of Nuxt.

...

> I reopening this for others to see. The module is still not compatible with nuxt3 since there is no production-ready version.

...

For now, you can manually import `gsap` to your `Nuxt 3` project.

As for `ScrollSmoother` i suggest you read official Gsap [guidelines](https://greensock.com/scrollsmoother/) and video how to implement it inside your project.

Also, you can use it with `nuxt-gsap-module` but in Nuxt 2 projects. Keep in mind that [ScrollSmoother](https://github.com/ivodolenc/nuxt-gsap-module#scrollsmoother) is a [Club Premium](https://github.com/ivodolenc/nuxt-gsap-module#club-greensock-plugins) plugin.

**Comment by BenjaminOddou** [comment]
> I reopening this for others to see. The module is still not compatible with `nuxt3` since there is no `production-ready` version.

Hello @ivodolenc ! 👋 The first version of Nuxt 3 was released today. Will you plan to update this module to be compatible with Nuxt 3 ? GSAP is overall compatible with Nuxt 3 already but I think there is room for improvement. Your module is already used and super appreciated by Nuxt 2 users, and I am pretty sure that it will be loved with Nuxt 3 🙂

**Comment by bonomite** [comment]
♥️

**Comment by ivodolenc** [comment]
@BenjaminOddou Hi and thanks for your interest. Yes, I'm definitely planning to add support for Nuxt 3, not only for the gsap-module, but also for all the other open source nuxt modules on my profile.

I can't promise an exact date since the new version brings significant changes and a lot of code needs to be rewritten (also the new modules require typescript support), but hopefully soon.

Also, need to see how to handle this in the best way since version 2 and 3 are not compatible. I would like to keep support for version 2 if possible.

**Comment by bonomite** [comment]
Appreciate all your hard work!

**Comment by khaledOghli** [comment]
Hi @ivodolenc , Thanks for a great package it's awesome, and me too I hope you will find time to upgrade it to nuxt 3.

**Comment by leosin** [comment]
Is there any way to import gsap globally, before the gsap module for nuxt3 upgrade?

**Comment by ivodolenc** [comment]
> Is there any way to import gsap globally, before the gsap module for nuxt3 upgrade?

At this point, no. To work properly in Nuxt 3, the module needs to be completely rewritten in typescript, and this takes a lot of time, mostly for docs, types, and examples.

I don't have much time to do it for free at the moment. If enough people can be gathered who would like to sponsor this project, I am willing to invest the time to update it to the latest version with proper support.

Please understand that I also need to somehow compensate for the time spent on this project. Anyway, thank you all for your interest.

**Comment by andresclua** [comment]
hey @ivodolenc , open to support / help you out if needed.

**Comment by ivodolenc** [comment]
@andresclua Thanks for the offer, I appreciate it. I'll tag you here when I need it 👍

**Comment by ivodolenc** [comment]
Hi guys, I finally updated the module so feel free to try the new version.

The module is optimized and supports nuxt 3 with typescript. Have fun!
