### ISSUE TITLE
How to proxy locomotive with Scroll Trigger

### ISSUE THREAD

**Issue by Sananes** [ivodolenc/nuxt-gsap-module#27]
Hey buddy, 

As always thank you for your hard work on all this. How do I get `locomotive` and `ScrollTrigger` to work nicely together?

I've tried a couple of attempts but I am failing. Just wondered if you've managed to make those two things work together nicely?

**Comment by ivodolenc** [comment]
Hi, [here](<https://greensock.com/docs/v3/Plugins/ScrollTrigger/static.scrollerProxy()>) you can find some official `examples` and detailed `information` about the `ScrollTrigger.scrollerProxy`.

Example -> [Locomotive Scroll + ScrollTrigger](https://codepen.io/GreenSock/pen/zYrELYe)
