### ISSUE TITLE
Support for GSAP 3.10.

### ISSUE THREAD

**Issue by Usagino** [ivodolenc/nuxt-gsap-module#31]
Hi 
3.10 is coming to everyone's favorite GreenSock.
I am a lover of Nuxt-gsap-module, when exactly will this module be ready for 3.10? I am looking forward to it as much as Santa is coming.

**Comment by ivodolenc** [comment]
Hi 👋🏻  

Thanks for your interest in this module, I'm glad you like it 👍🏻

I just updated the `module` and `GSAP` to the latest version.

**What's New**
- `Observer` plugin → [More info](https://github.com/ivodolenc/nuxt-gsap-module#observer)
- `ScrollSmoother` plugin → [More info](https://github.com/ivodolenc/nuxt-gsap-module#scrollsmoother)
- Full list of improvements and fixes → [See release](https://github.com/greensock/GSAP/releases/tag/3.10.0)

Feel free to try it! Happy coding 🥳

---
Available in the latest version: `1.7.0`

**Comment by ivodolenc** [comment]
Closing this as resolved.

**Comment by Usagino** [comment]
What? ! Really!
Thank you 💚
