### ISSUE TITLE
Can't get access to ScrollSmoother club plugin

### ISSUE THREAD

**Issue by nicolaselielll** [ivodolenc/nuxt-gsap-module#32]
Hello,

I'm trying to use the ScrollSmoother club plugin in my app but when I log this.$scrollSmoother I get undefined even tho my SplitText plugin works perfectly fine. Could this be an issue with the module because my other club plugin works but ScrollSmoother does not.

**Comment by ivodolenc** [comment]
Hi,

Thanks for reporting this. `Module` imports all plugins according to the official `gsap` import guidelines.

After you updated the `module` to version `1.7.0`, did you also update the `Club plugins` to the latest version `3.10.2`?

Example of `package.json` file for `Club plugins`:

```json
{
  "dependencies": {
    "@gsap/member": "npm:@gsap/member@3.10.2"
  },
  "devDependencies": {
    "nuxt-gsap-module": "^1.7.0"
  }
}
```
Feel free to try it again and let me know if everything works as expected.

**Comment by nicolaselielll** [comment]
Thanks a lot, It works now! I updated nuxt-gsap-module to 1.7.0.

**Comment by ivodolenc** [comment]
Awesome! Np, I'm glad it worked.

**Comment by nicolaselielll** [comment]
Hey, 

I tried to add the smooth scroll to my page but It does not add it. However now it does not throw any errors when I do this.ScrollSmoother.create({})

**Comment by ivodolenc** [comment]
It's difficult to say where the issue is without insight into more code.

According to official [docs](https://greensock.com/docs/v3/Plugins/ScrollSmoother), `ScrollSmoother` depends on the `ScrollTrigger`, so both plugins must be activated before you can use them.

```js
// nuxt.config.js

export default {
  gsap: {
    extraPlugins: {
      scrollTrigger: true
    },
    clubPlugins: {
      scrollSmoother: true
    }
  }
}
```

Also, put your code in the `mounted()` hook directly or via `methods`.
