### ISSUE TITLE
ScrollTrigger not working

### ISSUE THREAD

**Issue by andresclua** [ivodolenc/nuxt-gsap-module#34]
I'm having an issue with scrolltriggers.
Is not working on my end.

`<template>
  <div>
    <section style="height: 150vh"></section>
    <h1
      class="title"
      v-gsap.to="{
        scrollTrigger: {
          trigger: '.title',
          start: 'center bottom',
          end: 'center top',
          scrub: true,
          markers: true
        },
        x: 500
      }"
    >
      Nuxt GSAP Module
    </h1>
    <section style="height: 150vh"></section>
  </div>
</template>

export default{
  mounted(){
    console.log(this.$ScrollTrigger)
  }
}

<style>
.page-index {
  color: #e2e8f0;
  background-color: #2f495e;
  min-height: 100vh;
}
.content {
    margin-top:500px ;
  width: 100vw;
  min-height: 300vh;
}
.box {
  width: 100px;
  height: 100px;
  background-color: #00c58e;
}
</style>`

and my nuxt.config.js looks like
`    buildModules: [
        "@nuxtjs/device",
        "nuxt-gsap-module",
    ],

    gsap: {
        extraPluggins: {
            scrollTo: true,
            scrollTrigger: true,
        },
    },`
    
Strange thing is that I in order projects without problems.
Using nuxt 2.15.7

**Comment by ivodolenc** [comment]
Hi, I just tested it and the module works fine.

I see from your code that you have a typo in the `extraPlugins` option.

Try the code below:

- nuxt: `2.15.8`
- nuxt-gsap-module: `1.7.1`

```js
// nuxt.config.js

export default {
  buildModules: ['nuxt-gsap-module'],

  gsap: {
    extraPlugins: {
      scrollTo: true,
      scrollTrigger: true
    }
  }
}
```

```html
<!-- index.vue -->

<template>
  <h1>nuxt-gsap-module</h1>
</template>

<script>
  export default {
    mounted() {
      console.log(this.$ScrollTrigger)
    }
  }
</script>
```
