### ISSUE TITLE
Typescript Issue $gsap not found

### ISSUE THREAD

**Issue by king-11** [ivodolenc/nuxt-gsap-module#35]
I have a nuxt 2 application using `nuxt-gsap-module` when I try to access `this.$gsap` inside any project, it shows errors for $gsap not found. The same error populates down during build and causes issue even though I have it in `buildModules` for `nuxt.config.ts`

**Comment by ivodolenc** [comment]
Hi and thanks for your interest in this module.

I haven't tested this module in `typescript` setup so I'm not sure if it works well in that environment. However, you can import `gsap` manually and use it as recommended by official `Nuxt 2` guidelines in typescript projects.

**Comment by king-11** [comment]
Like other nuxt modules is it possible that we can export types such that user can add it to `tsconfig.json`

**Comment by king-11** [comment]
Thanks will take a look
