### ISSUE TITLE
Module Error #BUG#

### ISSUE THREAD

**Issue by M-Barari** [ivodolenc/nuxt-gsap-module#5]
Hi. I just installed your plugin and got this error (missed or typo) in your codes ! :)

![Screenshot 2021-03-04 132645](https://user-images.githubusercontent.com/63962449/109953963-fe499900-7cf5-11eb-8d57-0e75c493598d.png)

this is my nuxt.config.js

```javascript
gsap: {
    extraPlugins: {
      cssRule: false,
      draggable: false,
      easel: false,
      motionPath: false,
      pixi: false,
      text: false,
      scrollTo: false,
      scrollTrigger: false
    },
    extraEases: {
      expoScaleEase: false,
      roughEase: false,
      slowMo: false,
    }
  },
```

**Comment by ivodolenc** [comment]
Hi, thanks for reporting.

Fixed in `v1.2.1`.
