### ISSUE TITLE
Does it work with Nuxt Composition API?

### ISSUE THREAD

**Issue by psyCodelist** [ivodolenc/nuxt-gsap-module#7]
Hi, 

Thanks for the awesome module!

Is it possible to use it with Composition  API? is there any code sample of how to import and use it?

Many thanks!

**Comment by ivodolenc** [comment]
Hi, thanks for your interest in this module.

To be honest, I'm not familiar with `@nuxtjs/composition-api` at the moment, so I can't give you an example (I have to read the documentation and explore examples first). But feel free to give it a try 😉 👍

As stated in the official documentation:

> **Note**: the main aim is to allow experimentation and feedback before the final release of Nuxt 3. The API of Nuxt-specific methods will likely change before Nuxt 3 is released.

I believe that Nuxt 3 will bring some inevitable changes so all modules will have to adapt to the new system. I will wait for the official `v3` release and of course add support for new versions.

**Comment by maxarias-io** [comment]
I figured I'd leave a comment for anyone else stumbling into this.

With the composition API it's pretty much the same thing, but instead of `this` you get the context:
```
...
setup() {
    const context = useContext();
    
    onMounted(() => {
      // @ts-ignore
      const gsap = context.$gsap;
...
```

Everything seems to work fine otherwise. :)
